apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80           # Service port
    targetPort: 80     # Container port
    nodePort: 30080    # External port on each node (within 30000-32767)
