apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    app: app1
spec:
  type: NodePort
  selector:
    app: app1
  ports:
    - port: 80           # The port exposed by the service
      targetPort: 80     # The port your app container listens on
      protocol: TCP
      nodePort: 30081    # External port on the node (optional; auto-assigned if omitted)


#Ingress for vote.k8sb32.xyz
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-ingress-1
  namespace: demoapp1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: radius.anrsservice.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app1
                port:
                  number: 80

